### ISSUE TITLE
Is there a plan to support older versions of macos?

### ISSUE THREAD

**Issue by iamazy** [AugmendTech/CrabGrab#17]

**Comment by OutOfTheVoid** [comment]
Hey there. It's not something we're currently planning to support, but we're open to contributions. The difficulty with this is that there's no pre-ScreenCaptureKit API designed for (performant) window capture. 

It may be possible to use [CGDisplayStream](https://developer.apple.com/documentation/coregraphics/1455170-cgdisplaystreamcreate?language=objc), updating the source rectangle every time the window moves or resizes, and recreating when windows transition between displays, but that's out of scope for us currently, and would likely suffer from framing problems, and the inability to capture just the target window when it's occluded. For reference, here are the option keys that can be set on a CGDisplayStream: [Display Stream Optional Property Keys](https://developer.apple.com/documentation/coregraphics/quartz_display_services/display_stream_optional_property_keys?language=objc)

**Comment by OutOfTheVoid** [comment]
I'm closing this issue as not planned, but for anyone who might want to take this on, feel free to create a new issue.
